# Created: 2025-06-13 23:47:19
# Updated: 2026-03-18 20:38:08
# Language: Docker Compose version v5.1.0
# Images:
#    - rqlite/rqlite:9.4.5
# Project: rqlite Single-Node

name: rqliteSingleNode

services:

  myrqlite-service-1:
    image: rqlite/rqlite:latest
    container_name: myrqlite-container-1
    hostname: myrqlite-host-1
    volumes:
      - rqlite-data-node-1:/rqlite/file
    ports:
      - "4001:4001"
      - "4002:4002"
    environment:
      NODE_ID: myrqlite-node-1
      HTTP_ADDR: myrqlite-host-1:4001
      RAFT_ADDR: myrqlite-host-1:4002
      SQLITE_EXTENSIONS: "sqlean,sqlite-vec,misc"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://myrqlite-host-1:4001/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
    rqlite-data-node-1: {}
